### ISSUE TITLE
AdvancedForm virion

### ISSUE THREAD

**Issue by NhanAZ** [sky-min/pmmp-plugin-ideas#1]
A virion that allows to send a form like this to the player

![unknown](https://user-images.githubusercontent.com/60387689/188267139-0ed52d74-25c4-4256-be2e-175ac1489419.png)

**Comment by sky-min** [comment]
This is NPCDialogue.

**Comment by NhanAZ** [comment]
> https://github.com/refteams/libNpcDialogue
