### ISSUE TITLE
`frozen_effect`

### ISSUE THREAD

**Issue by NhanAZ** [sky-min/pmmp-plugin-ideas#2]
A method that allows sending frozen effects to players

![unknown (1)](https://user-images.githubusercontent.com/60387689/188267262-1174a2c1-181a-4bc2-a996-759f20c1b4b5.png)

**Comment by sky-min** [comment]
virion?

**Comment by NhanAZ** [comment]
Yes

**Comment by sky-min** [comment]
I would like to provide vanilla functionality as well, but I don't have too much material. TT
https://github.com/sky-min/FrozenEffect

**Comment by NhanAZ** [comment]
I found this, maybe it's helpful.
https://minecraft.fandom.com/wiki/Damage#Freezing

**Comment by sky-min** [comment]
> I found this, maybe it's helpful. https://minecraft.fandom.com/wiki/Damage#Freezing

Thanks, But it's still not enough...
