### ISSUE TITLE
AchievementForm Virion

### ISSUE THREAD

**Issue by NhanAZ** [sky-min/pmmp-plugin-ideas#3]
A viron that allows submitting an achievement form to a player
It is quite similar to ToastPacket but ToastPacket does not support icons

![image](https://user-images.githubusercontent.com/60387689/189667235-32a07008-91d0-4a1a-80ea-9a907ef8d01e.png)

https://user-images.githubusercontent.com/60387689/189667268-f620345a-9aa5-477a-a471-48b6f453387e.mov

**Comment by sky-min** [comment]
I think it's impossible. :(
I'll look for it....

**Comment by NhanAZ** [comment]
`Player::sendToastNotification()` Icon is not yet supported but it works.
