### ISSUE TITLE
ServerSettingsForm virion

### ISSUE THREAD

**Issue by NhanAZ** [sky-min/pmmp-plugin-ideas#5]
A virion that allows developers to easily send ServerSettingsForms to players.

![Screenshot_2023-02-06-07-26-57-483_com mojang minecraftpe](https://user-images.githubusercontent.com/60387689/218008012-4eb3ff13-0b79-4eaa-9aa5-9d7a1ad36b2f.jpg)

Something looks like this: https://github.com/Frago9876543210/EasyForms#serversettingsform

**Comment by sky-min** [comment]
https://github.com/sky-min/ServerSettingForm
@NhanAZ
